# Generated by Django 5.2.4 on 2025-07-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendamodel',
            table='sales',
        ),
    ]
